"use strict";
const DEMO_USER_KEY="mente-demo-user",POINTS_KEY="mente-points",PROGRESS_KEY="mente-progress";
const page=document.body.dataset.page;
const pageInfo={
 roteiro:["Roteiro de Estudos","Um caminho personalizado para transformar dúvidas em domínio da Matemática."],
 modulos:["Módulos de Estudos","Estude a teoria em uma sequência clara antes de praticar."],
 explicacoes:["Explicações","Conceitos destrinchados em linguagem simples, com exemplos e conexões."],
 simulados:["Simulados","Treine com questões mais desafiadoras e controle de tempo."],
 videoaulas:["Vídeo Aulas","Uma curadoria de professores e aulas para complementar seus estudos."],
 desempenho:["Meu Desempenho","Entenda sua evolução e descubra qual deve ser o próximo passo."],
};
const nav=[['questoes.html','⌕','Busca de Questões'],['roteiro.html','◇','Roteiro de Estudos'],['modulos.html','▤','Módulos de Estudos'],['explicacoes.html','✦','Explicações'],['simulados.html','✓','Simulados'],['videoaulas.html','▷','Vídeo Aulas'],['desempenho.html','↗','Meu Desempenho']];
function user(){try{return JSON.parse(localStorage.getItem(DEMO_USER_KEY))}catch{return null}}
function points(){return Number(localStorage.getItem(POINTS_KEY)||0)}
function shell(content){const current=location.pathname.split('/').pop();const u=user()||{name:'Visitante',email:'visitante@mente.local'};document.body.innerHTML=`<aside class="sidebar"><a class="sidebar__brand" href="index.html" aria-label="M.E.N.T.E — página inicial" style="display:flex;width:160px;height:160px;margin:0 auto 24px;align-items:center;justify-content:center;overflow:visible;background:transparent;box-shadow:none"><img src="assets/logo-mente-original.png" alt="M.E.N.T.E — Matemática Enem Traduzida e Explicada" style="display:block;width:160px;height:160px;object-fit:contain;border-radius:0"></a><nav class="sidebar__nav"><p class="sidebar__group">Estudo e prática</p>${nav.map(([href,icon,label])=>`<a class="sidebar__link ${current===href?'is-active':''}" href="${href}"><span>${icon}</span>${label}</a>`).join('')}<a class="sidebar__link" href="index.html"><span>⌂</span>Página Inicial</a></nav><button class="sidebar__logout" id="logout-button">↪ Sair</button></aside><div class="page-shell"><header class="topbar"><button class="menu-toggle" id="menu-toggle">☰</button><div><p class="topbar__eyebrow">Sua jornada M.E.N.T.E</p><h1>${pageInfo[page][0]}</h1></div><div class="topbar__actions"><div class="score">★ <strong id="global-points">${points()}</strong><small> pontos</small></div><button class="user-menu"><span class="user-menu__avatar">${(u.name||u.email)[0].toUpperCase()}</span><span class="user-menu__copy"><small>Bem-vindo(a)</small><strong>${u.name||u.email.split('@')[0]}</strong></span></button></div></header>${content}</div><div class="sidebar-backdrop" id="sidebar-backdrop"></div>`;document.querySelector('#logout-button').onclick=()=>{localStorage.removeItem(DEMO_USER_KEY);location.replace('login.html')};const toggle=document.querySelector('#menu-toggle');toggle.onclick=()=>document.body.classList.toggle('sidebar-open');document.querySelector('#sidebar-backdrop').onclick=()=>document.body.classList.remove('sidebar-open')}
const modules=['Geometria','Funções','Estatística e Probabilidade','Matemática Financeira','Grandezas e Medidas','Gráficos e Tabelas'];
function card(icon,title,text,extra=''){return `<article class="portal-card"><span class="portal-card__icon">${icon}</span><h3>${title}</h3><p>${text}</p>${extra}</article>`}
const renderers={
 roteiro:()=>`<div class="roadmap">${modules.map((m,i)=>`<article class="portal-card roadmap-step"><strong>${i+1}</strong><div><span class="portal-card__tag">ETAPA ${i+1}</span><h3>${m}</h3><p>${['Fundamentos visuais, áreas, perímetros e sólidos.','Relações entre grandezas, gráficos e modelagem.','Leitura de dados, medidas de tendência e incerteza.','Porcentagens, juros e decisões financeiras.','Conversões, escalas, razões e proporcionalidade.','Leitura crítica e comparação de informações.'][i]}</p><div class="progress-track"><span style="width:${i===0?35:0}%"></span></div><a class="portal-button" href="modulos.html">Continuar etapa</a></div></article>`).join('')}</div>`,
 modulos:()=>`<div class="portal-grid">${modules.map((m,i)=>card(['📐','ƒ','📊','💰','⚖️','📈'][i],m,`${5+i} aulas curtas, exemplos resolvidos e uma lista de fixação.`,`<span class="portal-card__tag">${i===0?'EM ANDAMENTO':'DISPONÍVEL'}</span><br><a class="portal-button" href="explicacoes.html">Abrir módulo</a>`)).join('')}</div>`,
 explicacoes:()=>`<div class="portal-grid">${modules.map((m,i)=>card('💡',m,['Formas, decomposição, áreas, semelhança e visão espacial.','Como reconhecer leis, taxas de variação, zeros e vértices.','Média, mediana, dispersão e cálculo de probabilidades.','Porcentagem como fator, juros simples e compostos.','Unidades, escalas e relações direta ou inversamente proporcionais.','Eixos, escalas, tendências e armadilhas de interpretação.'][i],'<button class="portal-button">Ler explicação</button>')).join('')}</div>`,
 simulados:()=>`<div class="portal-grid">${card('⏱️','Simulado diagnóstico','15 questões de nível intermediário para identificar lacunas.','<span class="portal-card__tag">30 MIN · +150 PTS</span><br><button class="portal-button sim-start">Começar</button>')}${card('🔥','Desafio ENEM','20 questões difíceis e contextualizadas de edições anteriores.','<span class="portal-card__tag">60 MIN · +300 PTS</span><br><button class="portal-button sim-start">Começar</button>')}${card('🎯','Treino por matéria','Monte um simulado apenas com os assuntos que precisa revisar.','<span class="portal-card__tag">PERSONALIZADO</span><br><a class="portal-button" href="questoes.html">Selecionar questões</a>')}</div>`,
 videoaulas:()=>`<div class="portal-grid">${[['Professor Ferretto','Matemática completa e resolução de exercícios','https://www.youtube.com/@professorferretto'],['Gis com Giz Matemática','Aulas visuais e fundamentos passo a passo','https://www.youtube.com/@Giscomgiz'],['Matemática Rio','Estratégias para ENEM e vestibulares','https://www.youtube.com/@MatematicaRio'],['Equaciona com Paulo Pereira','Resoluções detalhadas de Matemática','https://www.youtube.com/@equacionamatematica']].map(v=>card('▶️',v[0],v[1],`<a class="portal-button" target="_blank" rel="noopener" href="${v[2]}">Ver canal ↗</a>`)).join('')}</div>`,
 desempenho:()=>{const answers=Object.values(JSON.parse(localStorage.getItem('mente-answers')||'{}'));const correct=answers.filter(answer=>answer.correct).length;return `<div class="portal-grid">${card('⭐',`${points()} pontos`,'Ganhe 10 pontos por questão correta e bônus nos simulados.','<span class="portal-card__tag">PONTUAÇÃO TOTAL</span>')}${card('✅',`${answers.length} questões respondidas`,`${correct} acertos registrados. Continue praticando para construir consistência.`,`<div class="progress-track"><span style="width:${Math.min(answers.length/30*100,100)}%"></span></div>`)}${card('🔁','Revisão recomendada',answers.length?'Abra a aba Respondidas para rever enunciados, respostas e explicações.':'Comece por Geometria e Funções para gerar seu diagnóstico.','<a class="portal-button" href="questoes.html">Revisar questões</a>')}</div>`}
};
shell(`<main class="portal-main"><section class="portal-hero"><h2>${pageInfo[page][0]}</h2><p>${pageInfo[page][1]}</p></section>${renderers[page]()}</main>`);
document.querySelectorAll('.sim-start').forEach(b=>b.onclick=()=>alert('O construtor do simulado está preparado. As alternativas e o cronômetro serão adicionados na próxima etapa.'));
