"use strict";
const question=JSON.parse(localStorage.getItem("mente-selected-question")||"null");
const root=document.querySelector("#question-content");
const pointsKey="mente-points",progressKey="mente-progress";
document.querySelector("#points").textContent=localStorage.getItem(pointsKey)||0;

function lagoonDiagram(){return `<figure class="lagoon-diagram"><svg viewBox="0 0 430 285" role="img" aria-labelledby="lagoon-title lagoon-desc"><title id="lagoon-title">Ciclovia circular ao redor de uma lagoa</title><desc id="lagoon-desc">Lagoa circular azul, ciclovia cinza e região de alcance de duzentos metros para cada lado do ponto P.</desc><circle cx="190" cy="142" r="103" fill="#10add2"/><circle cx="190" cy="142" r="112" fill="none" stroke="#d8dee5" stroke-width="12"/><circle cx="190" cy="142" r="119" fill="none" stroke="#263747" stroke-width="2"/><path d="M269 58 A112 112 0 0 1 301 103" fill="none" stroke="#4b5563" stroke-width="13" stroke-linecap="round"/><circle cx="287" cy="79" r="5" fill="#172535"/><text x="276" y="99" font-size="16" font-style="italic">P</text><path d="M289 67 L337 30 M299 87 L353 63" stroke="#172535" stroke-width="1.5"/><text x="338" y="29" font-size="14">200 m</text><text x="354" y="67" font-size="14">200 m</text></svg><figcaption>Cada policial protege até 200 m da ciclovia em cada direção a partir de sua posição.</figcaption></figure>`}

if(!question){root.innerHTML='<article class="portal-card"><h2>Questão não encontrada</h2><p>Volte ao catálogo e escolha uma questão para começar.</p><a class="portal-button" href="questoes.html">Ver questões</a></article>';}else{
 const context={"Geometria":"Analise cuidadosamente as dimensões e identifique quais formas compõem a situação. Faça um desenho auxiliar antes de escolher a fórmula.","Funções":"Observe quais grandezas variam, o valor inicial e a taxa de mudança. Traduza cada informação do contexto para uma expressão matemática.","Estatística e Probabilidade":"Organize os dados, identifique o total de casos e verifique qual medida estatística responde exatamente ao que foi perguntado.","Matemática Financeira":"Separe capital, taxa e tempo. Verifique se a variação é aditiva ou multiplicativa antes de realizar os cálculos.","Grandezas e Medidas":"Registre as unidades de cada grandeza e faça todas as conversões antes de montar a proporção.","Gráficos e Tabelas":"Leia título, eixos, escalas e unidades. Compare valores absolutos e percentuais sem confundi-los."}[question.category];
 const alternatives=question.options?`<fieldset class="answer-options"><legend>Escolha uma alternativa</legend>${question.options.map((option,index)=>`<label><input type="radio" name="answer" value="${index}"><strong>${String.fromCharCode(65+index)}</strong><span>${option}</span></label>`).join('')}</fieldset>`:"";
 root.innerHTML=`<section class="portal-hero"><h2>${question.examNumber?`Questão ${question.examNumber} · ENEM ${question.year}`:`Questão ${String(question.id).padStart(2,'0')}`}</h2><p>Leia sem pressa, destaque os dados relevantes e registre seu raciocínio antes de conferir a explicação.</p></section><article class="portal-card"><div class="question-detail__meta"><span>${question.category}</span><span>${question.topic}</span><span>ENEM ${question.year}</span><span>${'★'.repeat(question.stars)}${'☆'.repeat(5-question.stars)}</span></div><p class="question-statement">${question.detail||question.text}</p>${question.visual==='bikeCircle'?lagoonDiagram():''}${alternatives}<hr class="question-divider"><h3>Como começar</h3><p>${context}</p><textarea class="working-area" id="working" aria-label="Seu raciocínio" placeholder="Anote os dados, a estratégia, os cálculos e sua conclusão..."></textarea><button class="portal-button" id="complete">Responder e concluir · +10 pts</button><p id="feedback" class="answer-feedback" role="status"></p></article>`;
 document.querySelector('#complete').onclick=()=>{const feedback=document.querySelector('#feedback');if(question.options){const selected=document.querySelector('input[name="answer"]:checked');if(!selected){feedback.textContent='Escolha uma alternativa antes de concluir.';feedback.dataset.type='error';return}if(Number(selected.value)!==question.correct){feedback.textContent='Ainda não. Revise o comprimento da circunferência e quanto da ciclovia cada policial consegue proteger.';feedback.dataset.type='error';return}}let done=JSON.parse(localStorage.getItem(progressKey)||'[]');if(done.includes(question.id)){feedback.textContent='Resposta correta! Você já concluiu esta questão.';feedback.dataset.type='success';return}done.push(question.id);localStorage.setItem(progressKey,JSON.stringify(done));const total=Number(localStorage.getItem(pointsKey)||0)+10;localStorage.setItem(pointsKey,total);document.querySelector('#points').textContent=total;feedback.textContent='Resposta correta! Você ganhou 10 pontos. A resolução completa será adicionada na etapa de explicações.';feedback.dataset.type='success';};
}
