"use strict";
const question=JSON.parse(localStorage.getItem("mente-selected-question")||"null");
const root=document.querySelector("#question-content");
const pointsKey="mente-points",progressKey="mente-progress";
document.querySelector("#points").textContent=localStorage.getItem(pointsKey)||0;
if(!question){root.innerHTML='<article class="portal-card"><h2>Questão não encontrada</h2><p>Volte ao catálogo e escolha uma questão para começar.</p><a class="portal-button" href="questoes.html">Ver questões</a></article>';}else{
 const context={"Geometria":"Analise cuidadosamente as dimensões e identifique quais formas compõem a situação. Faça um desenho auxiliar antes de escolher a fórmula.","Funções":"Observe quais grandezas variam, o valor inicial e a taxa de mudança. Traduza cada informação do contexto para uma expressão matemática.","Estatística e Probabilidade":"Organize os dados, identifique o total de casos e verifique qual medida estatística responde exatamente ao que foi perguntado.","Matemática Financeira":"Separe capital, taxa e tempo. Verifique se a variação é aditiva ou multiplicativa antes de realizar os cálculos.","Grandezas e Medidas":"Registre as unidades de cada grandeza e faça todas as conversões antes de montar a proporção.","Gráficos e Tabelas":"Leia título, eixos, escalas e unidades. Compare valores absolutos e percentuais sem confundi-los."}[question.category];
 root.innerHTML=`<section class="portal-hero"><h2>Questão ${String(question.id).padStart(2,'0')}</h2><p>Leia sem pressa, destaque os dados relevantes e registre seu raciocínio antes de conferir a explicação.</p></section><article class="portal-card"><div class="question-detail__meta"><span>${question.category}</span><span>${question.topic}</span><span>Adaptada do ENEM ${question.year}</span><span>${'★'.repeat(question.stars)}${'☆'.repeat(5-question.stars)}</span></div><p class="question-statement">${question.text}</p><hr style="border:0;border-top:1px solid #e5eaf1;margin:24px 0"><h3>Como começar</h3><p>${context}</p><label for="working"><strong>Seu raciocínio</strong></label><textarea class="working-area" id="working" placeholder="Anote os dados, a estratégia, os cálculos e sua conclusão..."></textarea><button class="portal-button" id="complete">Marcar como concluída · +10 pts</button><p id="feedback" role="status"></p></article>`;
 document.querySelector('#complete').onclick=()=>{let done=JSON.parse(localStorage.getItem(progressKey)||'[]');if(done.includes(question.id)){document.querySelector('#feedback').textContent='Você já concluiu esta questão.';return}done.push(question.id);localStorage.setItem(progressKey,JSON.stringify(done));const total=Number(localStorage.getItem(pointsKey)||0)+10;localStorage.setItem(pointsKey,total);document.querySelector('#points').textContent=total;document.querySelector('#feedback').textContent='Questão concluída! Você ganhou 10 pontos. A explicação completa será adicionada na próxima etapa.';};
}
